name: Build & Publish Image

on:
  push:
    branches: ["develop", "ci-test*"]
    tags: ["v*"]
    paths: ["src/GZCTF/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/GZCTF

    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prebuild Project
        run: |
          npm i -g pnpm
          dotnet build "CTFServer.csproj" -c Release -o build

      - name: Publish Project
        run: |
          dotnet publish "CTFServer.csproj" -c Release -o publish/linux/amd64 -r linux-x64 --no-self-contained /p:PublishReadyToRun=true
          dotnet publish "CTFServer.csproj" -c Release -o publish/linux/arm64 -r linux-arm64 --no-self-contained /p:PublishReadyToRun=true
        env:
          VITE_APP_BUILD_TIMESTAMP: ${{ steps.time.outputs.time }}
          VITE_APP_GIT_SHA: ${{ github.sha }}
          VITE_APP_GIT_NAME: ${{ github.ref_name }}
      - name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp -r bin/Release/* ./artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: CTFServer Upload
          path: ./artifact/
